/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-primary": "#610034",
        "primary-container": "#ff6ea9",
        "error-container": "#a70138",
        "outline-variant": "#454852",
        "primary-fixed-dim": "#ff4f9e",
        "on-secondary": "#465800",
        outline: "#737580",
        "on-primary-fixed-variant": "#5c0031",
        "on-tertiary": "#5f5f5d",
        "on-primary-fixed": "#000000",
        primary: "#ff88b5",
        "on-tertiary-fixed-variant": "#6d6d6b",
        "surface-variant": "#212532",
        "secondary-container": "#526600",
        "secondary-fixed": "#c9f236",
        "surface-tint": "#ff88b5",
        "inverse-primary": "#ba0068",
        "surface-bright": "#272c3a",
        background: "#0b0e17",
        surface: "#0b0e17",
        "tertiary-fixed-dim": "#f2f0ed",
        tertiary: "#fbf9f6",
        "inverse-surface": "#faf8ff",
        "on-error-container": "#ffb2b9",
        "surface-container-high": "#1b1f2b",
        "surface-container-low": "#10131d",
        "surface-container-highest": "#212532",
        "surface-container": "#161924",
        "error-dim": "#d73357",
        "secondary-dim": "#bbe425",
        "tertiary-container": "#edebe8",
        "on-tertiary-container": "#575755",
        "inverse-on-surface": "#52555f",
        "on-secondary-fixed": "#364500",
        "on-error": "#490013",
        "primary-fixed": "#ff6ea9",
        "on-surface": "#eff0fd",
        "surface-container-lowest": "#000000",
        "on-background": "#eff0fd",
        secondary: "#c9f236",
        error: "#ff6e84",
        "tertiary-fixed": "#ffffff",
        "surface-dim": "#0b0e17",
        "on-primary-container": "#4b0027",
        "primary-dim": "#ff69a7",
        "on-secondary-container": "#f0ffb9",
        "on-secondary-fixed-variant": "#4f6300",
        "on-surface-variant": "#a8aab7",
        "on-tertiary-fixed": "#50504e",
        "tertiary-dim": "#edebe8",
      },
      borderRadius: {
        DEFAULT: "1rem",
        lg: "2rem",
        xl: "3rem",
        full: "9999px",
      },
      fontFamily: {
        headline: ["Inter", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
      },
      keyframes: {
        scroll: {
          "0%": { transform: "translateX(0)" },
          "100%": { transform: "translateX(-50%)" },
        },
        float: {
          "0%, 100%": { transform: "translateY(0px)" },
          "50%": { transform: "translateY(-12px)" },
        },
        fadeUp: {
          "0%": { opacity: "0", transform: "translateY(20px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
      },
      animation: {
        scroll: "scroll 30s linear infinite",
        float: "float 6s ease-in-out infinite",
        "fade-up": "fadeUp 0.6s ease-out forwards",
      },
    },
  },
  plugins: [],
};
